export const appTypes = {
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',

  SHOW_ERROR: 'SHOW_ERROR',
  HIDE_ERROR: 'HIDE_ERROR'
};

export const postTypes = {
  FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',

  FETCH_POSTS_BY_CATEGORY_ERROR: 'FETCH_POSTS_BY_CATEGORY_ERROR',
  FETCH_POSTS_BY_CATEGORY_SUCCESS: 'FETCH_POSTS_BY_CATEGORY_SUCCESS',

  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_ERROR: 'DELETE_POST_ERROR',

  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_ERROR: 'CREATE_POST_ERROR',

  CREATE_POST_CAT_SUCCESS: 'CREATE_POST_CAT_SUCCESS',
  CREATE_POST_CAT_ERROR: 'CREATE_POST_CAT_ERROR'
};
